import type { ServiceCategory, BusinessHours } from "./types"

export const serviceCategories: ServiceCategory[] = [
  {
    id: "manikure",
    name: "MANICURE",
    nameVi: "LÀM MÓNG TAY",
    nameDe: "MANIKÜRE",
    services: [
      {
        id: "mani-massage",
        name: "Manicure incl. Massage",
        nameVi: "Làm móng tay kèm massage",
        nameDe: "inkl. Massage",
        price: 15,
        duration: 45,
        category: "MANICURE",
        categoryVi: "LÀM MÓNG TAY",
        categoryDe: "MANIKÜRE",
      },
      {
        id: "mani-color",
        name: "Manicure incl. Clear Coat / Color",
        nameVi: "Làm móng tay kèm sơn trong/màu",
        nameDe: "inkl. Klar-Lack / Farb-lack",
        price: 25,
        priceFrom: true,
        duration: 45,
        category: "MANICURE",
        categoryVi: "LÀM MÓNG TAY",
        categoryDe: "MANIKÜRE",
      },
    ],
  },
  {
    id: "pedikure",
    name: "PEDICURE",
    nameVi: "LÀM MÓNG CHÂN",
    nameDe: "PEDIKÜRE",
    services: [
      {
        id: "pedi-massage",
        name: "Pedicure incl. Massage",
        nameVi: "Làm móng chân kèm massage",
        nameDe: "inkl. Massage",
        price: 28,
        duration: 45,
        category: "PEDICURE",
        categoryVi: "LÀM MÓNG CHÂN",
        categoryDe: "PEDIKÜRE",
      },
      {
        id: "pedi-clear",
        name: "Pedicure incl. Clear Coat",
        nameVi: "Làm móng chân kèm sơn trong",
        nameDe: "inkl. Klar-Lack",
        price: 35,
        duration: 45,
        category: "PEDICURE",
        categoryVi: "LÀM MÓNG CHÂN",
        categoryDe: "PEDIKÜRE",
      },
      {
        id: "pedi-color",
        name: "Pedicure incl. Color",
        nameVi: "Làm móng chân kèm sơn màu",
        nameDe: "Farb-lack",
        price: 40,
        priceFrom: true,
        duration: 45,
        category: "PEDICURE",
        categoryVi: "LÀM MÓNG CHÂN",
        categoryDe: "PEDIKÜRE",
      },
    ],
  },
  {
    id: "pulver-gel",
    name: "POWDER GEL",
    nameVi: "GEL BỘT",
    nameDe: "PULVER-GEL",
    services: [
      {
        id: "pulver-neu",
        name: "New Set",
        nameVi: "Bộ mới",
        nameDe: "Neumodellage",
        price: 37,
        duration: 45,
        category: "POWDER GEL",
        categoryVi: "GEL BỘT",
        categoryDe: "PULVER-GEL",
      },
      {
        id: "pulver-french",
        name: "French",
        nameVi: "French",
        nameDe: "French",
        price: 45,
        duration: 45,
        category: "POWDER GEL",
        categoryVi: "GEL BỘT",
        categoryDe: "PULVER-GEL",
      },
      {
        id: "pulver-gellack",
        name: "Gel Polish",
        nameVi: "Sơn gel",
        nameDe: "Gel-lack",
        price: 42,
        duration: 45,
        category: "POWDER GEL",
        categoryVi: "GEL BỘT",
        categoryDe: "PULVER-GEL",
      },
      {
        id: "pulver-auff",
        name: "Refill",
        nameVi: "Đắp bù",
        nameDe: "Auffüllen",
        price: 35,
        duration: 45,
        category: "POWDER GEL",
        categoryVi: "GEL BỘT",
        categoryDe: "PULVER-GEL",
      },
      {
        id: "pulver-auff-french",
        name: "Refill French",
        nameVi: "Đắp bù French",
        nameDe: "Auffüllen French",
        price: 43,
        duration: 45,
        category: "POWDER GEL",
        categoryVi: "GEL BỘT",
        categoryDe: "PULVER-GEL",
      },
      {
        id: "pulver-auff-gellack",
        name: "Refill Gel Polish",
        nameVi: "Đắp bù sơn gel",
        nameDe: "Auffüllen Gel-lack",
        price: 37,
        duration: 45,
        category: "POWDER GEL",
        categoryVi: "GEL BỘT",
        categoryDe: "PULVER-GEL",
      },
    ],
  },
  {
    id: "flussig-gel",
    name: "LIQUID GEL",
    nameVi: "GEL LỎNG",
    nameDe: "FLÜSSIG-GEL",
    services: [
      {
        id: "flussig-neu",
        name: "New Set",
        nameVi: "Bộ mới",
        nameDe: "Neumodellage",
        price: 42,
        duration: 45,
        category: "LIQUID GEL",
        categoryVi: "GEL LỎNG",
        categoryDe: "FLÜSSIG-GEL",
      },
      {
        id: "flussig-french",
        name: "French",
        nameVi: "French",
        nameDe: "French",
        price: 50,
        duration: 45,
        category: "LIQUID GEL",
        categoryVi: "GEL LỎNG",
        categoryDe: "FLÜSSIG-GEL",
      },
      {
        id: "flussig-gellack",
        name: "Gel Polish",
        nameVi: "Sơn gel",
        nameDe: "Gel-lack",
        price: 45,
        duration: 45,
        category: "LIQUID GEL",
        categoryVi: "GEL LỎNG",
        categoryDe: "FLÜSSIG-GEL",
      },
      {
        id: "flussig-auff",
        name: "Refill",
        nameVi: "Đắp bù",
        nameDe: "Auffüllen",
        price: 35,
        duration: 45,
        category: "LIQUID GEL",
        categoryVi: "GEL LỎNG",
        categoryDe: "FLÜSSIG-GEL",
      },
      {
        id: "flussig-auff-french",
        name: "Refill French",
        nameVi: "Đắp bù French",
        nameDe: "Auffüllen French",
        price: 45,
        duration: 45,
        category: "LIQUID GEL",
        categoryVi: "GEL LỎNG",
        categoryDe: "FLÜSSIG-GEL",
      },
      {
        id: "flussig-auff-gellack",
        name: "Refill Gel Polish",
        nameVi: "Đắp bù sơn gel",
        nameDe: "Auffüllen Gel-lack",
        price: 40,
        duration: 45,
        category: "LIQUID GEL",
        categoryVi: "GEL LỎNG",
        categoryDe: "FLÜSSIG-GEL",
      },
    ],
  },
  {
    id: "shell-lack",
    name: "SHELLAC",
    nameVi: "SHELLAC",
    nameDe: "SHELL-LACK",
    services: [
      {
        id: "shell-lack",
        name: "Shellac",
        nameVi: "Shellac",
        nameDe: "Shell-Lack",
        price: 30,
        duration: 45,
        category: "SHELLAC",
        categoryVi: "SHELLAC",
        categoryDe: "SHELL-LACK",
      },
      {
        id: "shell-mani",
        name: "Shellac + Manicure",
        nameVi: "Shellac + Làm móng tay",
        nameDe: "Shell-Lack + Maniküre",
        price: 35,
        duration: 45,
        category: "SHELLAC",
        categoryVi: "SHELLAC",
        categoryDe: "SHELL-LACK",
      },
      {
        id: "shell-fuss",
        name: "Shellac Feet",
        nameVi: "Shellac chân",
        nameDe: "Shell-Lack (Fuß)",
        price: 30,
        duration: 45,
        category: "SHELLAC",
        categoryVi: "SHELLAC",
        categoryDe: "SHELL-LACK",
      },
      {
        id: "shell-pedi",
        name: "Shellac + Pedicure",
        nameVi: "Shellac + Làm móng chân",
        nameDe: "Shell-Lack + Pediküre",
        price: 45,
        duration: 45,
        category: "SHELLAC",
        categoryVi: "SHELLAC",
        categoryDe: "SHELL-LACK",
      },
    ],
  },
  {
    id: "sonstiges",
    name: "OTHERS",
    nameVi: "DỊCH VỤ KHÁC",
    nameDe: "SONSTIGES",
    services: [
      {
        id: "fuss-gel",
        name: "Foot Gel Modeling",
        nameVi: "Đắp gel chân",
        nameDe: "Fuß-Gelmodellage",
        price: 35,
        duration: 45,
        category: "OTHERS",
        categoryVi: "DỊCH VỤ KHÁC",
        categoryDe: "SONSTIGES",
      },
      {
        id: "design-finger",
        name: "Design per finger",
        nameVi: "Thiết kế mỗi ngón",
        nameDe: "Design pro Finger",
        price: 3,
        priceFrom: true,
        duration: 45,
        category: "OTHERS",
        categoryVi: "DỊCH VỤ KHÁC",
        categoryDe: "SONSTIGES",
      },
      {
        id: "design-komplett",
        name: "Full Design",
        nameVi: "Thiết kế toàn bộ",
        nameDe: "Design komplett",
        price: 15,
        duration: 45,
        category: "OTHERS",
        categoryVi: "DỊCH VỤ KHÁC",
        categoryDe: "SONSTIGES",
      },
      {
        id: "verlauf",
        name: "Gradient",
        nameVi: "Gradient",
        nameDe: "Verlauf",
        price: 45,
        duration: 45,
        category: "OTHERS",
        categoryVi: "DỊCH VỤ KHÁC",
        categoryDe: "SONSTIGES",
      },
      {
        id: "strass",
        name: "Rhinestones",
        nameVi: "Đá trang trí",
        nameDe: "Strasssteinchen",
        price: 0.5,
        priceFrom: true,
        duration: 45,
        category: "OTHERS",
        categoryVi: "DỊCH VỤ KHÁC",
        categoryDe: "SONSTIGES",
      },
      {
        id: "lack-glitzer",
        name: "Polish/Glitter",
        nameVi: "Sơn/Kim tuyến",
        nameDe: "Lack/Glitzer",
        price: 7,
        duration: 45,
        category: "OTHERS",
        categoryVi: "DỊCH VỤ KHÁC",
        categoryDe: "SONSTIGES",
      },
      {
        id: "nagelreparatur",
        name: "Nail Repair",
        nameVi: "Sửa móng",
        nameDe: "Nagelreparatur",
        price: 3,
        priceFrom: true,
        duration: 45,
        category: "OTHERS",
        categoryVi: "DỊCH VỤ KHÁC",
        categoryDe: "SONSTIGES",
      },
      {
        id: "ablosen",
        name: "Removal",
        nameVi: "Tháo móng",
        nameDe: "Ablösen",
        price: 15,
        duration: 45,
        category: "OTHERS",
        categoryVi: "DỊCH VỤ KHÁC",
        categoryDe: "SONSTIGES",
      },
      {
        id: "extra-lang",
        name: "Extra Long",
        nameVi: "Móng dài thêm",
        nameDe: "Extra Lang",
        price: 5,
        priceFrom: true,
        duration: 45,
        category: "OTHERS",
        categoryVi: "DỊCH VỤ KHÁC",
        categoryDe: "SONSTIGES",
      },
      {
        id: "chrom",
        name: "Chrom | Cat Eye",
        nameVi: "Chrom | Mắt mèo",
        nameDe: "Chrom | Cat Eye  ",
        price: 15,
        duration: 45,
        category: "OTHERS",
        categoryVi: "DỊCH VỤ KHÁC",  
        categoryDe: "SONSTIGES",
      },
    ],
  },
]

export const businessHours: BusinessHours[] = [
  { day: "Monday", dayVi: "Thứ Hai", dayDe: "Montag", open: "09:00", close: "19:00", closed: false },
  { day: "Tuesday", dayVi: "Thứ Ba", dayDe: "Dienstag", open: "09:00", close: "19:00", closed: false },
  { day: "Wednesday", dayVi: "Thứ Tư", dayDe: "Mittwoch", open: "09:00", close: "19:00", closed: false },
  { day: "Thursday", dayVi: "Thứ Năm", dayDe: "Donnerstag", open: "09:00", close: "19:00", closed: false },
  { day: "Friday", dayVi: "Thứ Sáu", dayDe: "Freitag", open: "09:00", close: "19:00", closed: false },
  { day: "Saturday", dayVi: "Thứ Bảy", dayDe: "Samstag", open: "09:00", close: "19:00", closed: false },
  { day: "Sunday", dayVi: "Chủ Nhật", dayDe: "Sonntag", open: "09:00", close: "19:00", closed: false },
]

export const galleryImages = [
 "/Gallery/Gallery-1.webp",
 "/Gallery/Gallery-2.webp",
 "/Gallery/Gallery-3.webp",
 "/Gallery/Gallery-4.webp",
 "/Gallery/Gallery-5.webp",
 "/Gallery/Gallery-6.webp",
 "/Gallery/Gallery-7.webp",
 "/Gallery/Gallery-8.webp",
]

export const contactInfo = {
  name: "Amici Nail Salon",
  address: "Kapellen Str 11, 76437 Rastatt , Germany",
  email: "phuonglinhdang89@gmail.com",
  phone: "0722 21656351 / 0176 43299127",
  instagram: "https://www.instagram.com/amici_nailsalon/",
}
